services:
  sp:
    build:
      context: .
      dockerfile: Dockerfile.sp
    ports:
      - "8000:8000"
    networks:
      - saml-network
    depends_on:
      - idp
    environment:
      - IDP_URL=http://idp:8080

  idp:
    build:
      context: .
      dockerfile: Dockerfile.idp
    ports:
      - "8080:8080"
    networks:
      - saml-network

networks:
  saml-network:
    driver: bridge






    